# Sidebar navigation

- label: "Introduction"
  link: "/"
- label: "Getting started"
  link: "/getting-started"
- label: First Scene
  items:
    - label: "First Things on the Screen"
      link: "/first-scene/first-render"
    - label: "Lights"
      link: "/first-scene/lights"
    - label: "Animation"
      link: "/first-scene/animation"
